from typing import Dict, List

from embeddings.vector_store import EmbeddingVectorStore
from services.llm import LLMService
from utils.prompt_builder import build_generation_prompt
from utils.response_parser import parse_test_case_response


class LLMEngine:
    def __init__(self):
        self.llm = LLMService()
        self.vector_store = EmbeddingVectorStore()

    def generate_from_jira_issue(self, issue_data: Dict, test_types: List[str]) -> List[Dict]:
        searchable_chunks = []
        summary = issue_data.get("summary", "")
        description = issue_data.get("description", "")
        acceptance_criteria = issue_data.get("acceptance_criteria", "")
        attachments = issue_data.get("attachments_text", []) or []

        if summary:
            searchable_chunks.append(summary)
        if description:
            searchable_chunks.append(description)
        if acceptance_criteria:
            searchable_chunks.append(acceptance_criteria)
        attachment_chunks = [x for x in attachments if x]
        searchable_chunks.extend(attachment_chunks)

        metadatas = []
        if summary:
            metadatas.append({"source": "summary"})
        if description:
            metadatas.append({"source": "description"})
        if acceptance_criteria:
            metadatas.append({"source": "acceptance_criteria"})
        metadatas.extend([{"source": "attachment"} for _ in attachment_chunks])

        self.vector_store.add_texts(
            searchable_chunks,
            metadatas=metadatas,
        )

        attachment_query = "\n".join(attachment_chunks[:2])
        semantic_context = self.vector_store.search(
            query=f"{summary}\n{description}\n{acceptance_criteria}\n{attachment_query}",
            top_k=3,
        )

        prompt = build_generation_prompt(issue_data, test_types, semantic_context)
        seed_payload = {
            "summary": summary or "Generated Test Cases",
            "source": "\n".join(searchable_chunks),
            "test_types": test_types,
        }
        raw_response = self.llm.generate_json(prompt, seed_payload)
        cases = parse_test_case_response(raw_response)

        final_cases = []
        for idx, case in enumerate(cases, start=1):
            normalized = dict(case)
            normalized["test_case_id"] = f"TC-{idx:03d}"
            if not normalized.get("steps"):
                normalized["steps"] = ["No steps generated by model."]
            final_cases.append(normalized)
        return final_cases
