from typing import Dict, List, Optional

from embeddings.vector_store import EmbeddingVectorStore
from services.llm import LLMService
from utils.prompt_builder import build_generation_prompt, build_locator_prompt
from utils.response_parser import parse_locator_response, parse_test_case_response


class LLMEngine:
    def __init__(self):
        self.llm = LLMService()
        self.vector_store = EmbeddingVectorStore()

    def generate_from_jira_issue(
        self,
        issue_data: Dict,
        test_types: List[str],
        model_id: Optional[str] = None,
    ) -> List[Dict]:
        searchable_chunks = []
        summary = issue_data.get("summary", "")
        description = issue_data.get("description", "")
        acceptance_criteria = issue_data.get("acceptance_criteria", "")
        custom_prompt = str(issue_data.get("custom_prompt", "")).strip()
        attachments = issue_data.get("attachments_text", []) or []

        if summary:
            searchable_chunks.append(summary)
        if description:
            searchable_chunks.append(description)
        if acceptance_criteria:
            searchable_chunks.append(acceptance_criteria)
        if custom_prompt:
            searchable_chunks.append(custom_prompt)
        attachment_chunks = [x for x in attachments if x]
        searchable_chunks.extend(attachment_chunks)

        metadatas = []
        if summary:
            metadatas.append({"source": "summary"})
        if description:
            metadatas.append({"source": "description"})
        if acceptance_criteria:
            metadatas.append({"source": "acceptance_criteria"})
        if custom_prompt:
            metadatas.append({"source": "custom_prompt"})
        metadatas.extend([{"source": "attachment"} for _ in attachment_chunks])

        self.vector_store.add_texts(
            searchable_chunks,
            metadatas=metadatas,
        )

        attachment_query = "\n".join(attachment_chunks[:2])
        semantic_context = self.vector_store.search(
            query=f"{summary}\n{description}\n{acceptance_criteria}\n{custom_prompt}\n{attachment_query}",
            top_k=3,
        )

        prompt = build_generation_prompt(issue_data, test_types, semantic_context)
        seed_payload = {
            "summary": summary or "Generated Test Cases",
            "source": "\n".join(searchable_chunks),
            "test_types": test_types,
        }
        raw_response = self.llm.generate_json(prompt, seed_payload, model_id=model_id)
        cases = parse_test_case_response(raw_response)

        final_cases = []
        for idx, case in enumerate(cases, start=1):
            normalized = dict(case)
            normalized["test_case_id"] = f"TC-{idx:03d}"
            if not normalized.get("steps"):
                normalized["steps"] = ["No steps generated by model."]
            final_cases.append(normalized)
        return final_cases

    def generate_locators(
        self,
        dom: str,
        framework: str,
        language: str,
        custom_prompt: str = "",
        model_id: Optional[str] = None,
    ) -> Dict:
        prompt = build_locator_prompt(
            dom=dom,
            framework=framework,
            language=language,
            custom_prompt=custom_prompt,
        )
        seed_payload = {
            "mode": "locator_generation",
            "dom": dom,
            "framework": framework,
            "language": language,
            "custom_prompt": custom_prompt,
        }
        raw_response = self.llm.generate_json(prompt, seed_payload, model_id=model_id)
        parsed = parse_locator_response(raw_response)
        return {
            "locators": parsed.get("locators", []),
            "test_template": parsed.get("test_template", ""),
            "model_used": self.llm.last_model_used,
        }
